apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-green
  labels:
    app: helloworld-green
    deployment: green
    version: 1.0.1 # concept of version could be important for your CD tools. 
spec: # here's what the deployment is going to create
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-green
      deployment: green # including blue key/value
      version: 1.0.1 # version (optional)
  template: 
    metadata:
      labels:
        app: helloworld-green
        deployment: green
        version: 1.0.1 # concept of version could be important for your CD tools. 
    spec:
      containers:
      - name: helloworld-green
        image: othom/flask:14
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
