apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
    deployment: blue
    version: 1.0.0 # concept of version could be important for your CD tools. 
spec: # here's what the deployment is going to create
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      deployment: blue # including blue key/value
      version: 1.0.0 # version (optional)
  template: 
    metadata:
      labels:
        app: helloworld
        deployment: blue
        version: 1.0.0 # concept of version could be important for your CD tools. 
    spec:
      containers:
      - name: helloworld
        image: ecarmona1992/project1:98
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
