apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  labels:
    name: helloworld-service
spec:
  type: LoadBalancer
  selector: # scans for deployments that match this selector (this is the green!)
    app: helloworld-green # this is the updated deployment to use
    deployment: green
    version: 1.0.1 # new version
  ports:
  - name: http 
    port: 8080
    targetPort: 5000

